backend:
  name: git-gateway
  branch: master

media_folder: "_site/Image"
public_folder: "/Image"

collections:
    name: "posts"
    label: "Posts"
    folder: "_site/_data"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
       { name: "title", widget: "string" }
       { name: "featuredImage", widget: "image" }   
