backend:
  name: git-gateway
  branch: master

media_folder: "_site/Image"
public_folder: "/Image"

collections:
  - name: "posts"
    label: "Posts"
    files:
    - file: "src/_data/posts.json"
      label: "Posts"
      name: "posts"
      fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Featured Image", name: "featuredImage", widget: "image" }
            widget: "list"