backend:
  name: git-gateway
  branch: master

media_folder: "_site/image"
public_folder: "/image"

collections:
  - name: "posts"
    label: "posts"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
